"""Nested cross-fitting for the PV Oracle and day-ahead forecast models."""

from __future__ import annotations

import json
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Final

import numpy as np
import pandas as pd
from sklearn.base import RegressorMixin
from sklearn.ensemble import HistGradientBoostingRegressor

from energy.data.builder import WEATHER_VARIABLES
from energy.data.splitting import SeasonalWeekKFold

PV_TARGET: Final = "pv_power_mean_w"
CONTEXT_FEATURES: Final = (
    "hour_sin",
    "hour_cos",
    "day_of_year_sin",
    "day_of_year_cos",
    "is_weekend",
    "horizon_hours",
)

ModelFactory = Callable[[int], RegressorMixin]


def load_pv_model_frame(project_root: str | Path, year: int = 2024) -> pd.DataFrame:
    """Join the day-ahead PV table with actual weather for Oracle training.

    The output retains forecast-weather fields for the deployable model and
    adds actual-weather fields solely for the Oracle upper-bound model.
    """

    root = Path(project_root)
    pv_path = root / "data" / "features" / "day_ahead_pv" / f"day_ahead_pv_{year}.parquet"
    oracle_path = root / "data" / "features" / "oracle_pv" / f"oracle_pv_{year}.parquet"
    pv = pd.read_parquet(pv_path)
    actual_columns = [f"weather_actual_{variable}" for variable in WEATHER_VARIABLES]
    oracle = pd.read_parquet(oracle_path, columns=["valid_time_utc", *actual_columns])
    frame = pv.merge(oracle, on="valid_time_utc", how="left", validate="one_to_one")
    required = [
        PV_TARGET,
        "week_index",
        *CONTEXT_FEATURES,
        *[f"weather_forecast_{variable}" for variable in WEATHER_VARIABLES],
        *actual_columns,
    ]
    frame = frame.dropna(subset=required).sort_values("valid_time_utc").reset_index(drop=True)
    if frame.empty:
        raise ValueError("No complete PV modelling rows after joining actual weather")
    return frame


@dataclass(frozen=True)
class PVExperimentResult:
    """Out-of-fold predictions and fold-level scores for both PV models."""

    oof_predictions: pd.DataFrame
    fold_metrics: pd.DataFrame
    average_fold_metrics: dict[str, float]
    pooled_oof_metrics: dict[str, float]

    def write(self, output_dir: str | Path) -> None:
        """Persist reproducible experiment artefacts."""

        destination = Path(output_dir)
        destination.mkdir(parents=True, exist_ok=True)
        self.oof_predictions.to_parquet(destination / "oof_predictions.parquet", index=False)
        self.fold_metrics.to_csv(destination / "fold_metrics.csv", index=False)
        (destination / "summary.json").write_text(
            json.dumps(
                {
                    "average_fold_metrics": self.average_fold_metrics,
                    "pooled_oof_metrics": self.pooled_oof_metrics,
                },
                ensure_ascii=False,
                indent=2,
            )
        )


class CrossFittedPVExperiment:
    """Evaluate an Oracle-assisted day-ahead PV forecaster without leakage.

    For every outer fold, the forecasting model only sees Oracle proxy values
    generated by Oracle models that were fitted without the target rows in the
    corresponding fold. Inner cross-fitting protects the outer training data;
    the final Oracle for the outer test fold is fitted solely on outer-train
    rows.
    """

    def __init__(
        self,
        *,
        outer_splits: int = 5,
        inner_splits: int = 5,
        random_state: int = 42,
        oracle_factory: ModelFactory | None = None,
        forecast_factory: ModelFactory | None = None,
    ) -> None:
        self.outer_splits = outer_splits
        self.inner_splits = inner_splits
        self.random_state = random_state
        self.oracle_factory = oracle_factory or _default_model_factory
        self.forecast_factory = forecast_factory or _default_model_factory

    def run(self, frame: pd.DataFrame) -> PVExperimentResult:
        """Run nested cross-fitting and return out-of-fold predictions and metrics."""

        _validate_model_frame(frame)
        outer_splitter = SeasonalWeekKFold(
            self.outer_splits,
            random_state=self.random_state,
        )
        fold_metrics: list[dict[str, float | int]] = []
        predictions: list[pd.DataFrame] = []

        for outer_fold in outer_splitter.split_with_metadata(frame):
            outer_train = frame.iloc[outer_fold.train_indices].reset_index(drop=True)
            outer_test = frame.iloc[outer_fold.test_indices].reset_index(drop=True)
            proxy_train = self._inner_oof_oracle_proxy(outer_train, outer_fold.fold_index)

            final_oracle = self.oracle_factory(self.random_state + 1_000 + outer_fold.fold_index)
            final_oracle.fit(_oracle_features(outer_train, weather_source="actual"), outer_train[PV_TARGET])
            proxy_test = _nonnegative(
                final_oracle.predict(_oracle_features(outer_test, weather_source="forecast"))
            )
            oracle_actual_test = _nonnegative(
                final_oracle.predict(_oracle_features(outer_test, weather_source="actual"))
            )

            forecaster = self.forecast_factory(self.random_state + 2_000 + outer_fold.fold_index)
            forecaster.fit(
                _forecast_features(outer_train, proxy_train),
                outer_train[PV_TARGET],
            )
            forecast_test = _nonnegative(
                forecaster.predict(_forecast_features(outer_test, proxy_test))
            )
            forecast_baseline = self.forecast_factory(
                self.random_state + 3_000 + outer_fold.fold_index
            )
            forecast_baseline.fit(
                _forecast_features(outer_train),
                outer_train[PV_TARGET],
            )
            baseline_test = _nonnegative(forecast_baseline.predict(_forecast_features(outer_test)))
            y_test = outer_test[PV_TARGET].to_numpy(dtype=float)

            fold_metrics.append(
                {
                    "outer_fold": outer_fold.fold_index,
                    "rows": len(outer_test),
                    "test_weeks": len(outer_fold.test_weeks),
                    **_metrics(y_test, oracle_actual_test, prefix="oracle"),
                    **_metrics(y_test, baseline_test, prefix="baseline"),
                    **_metrics(y_test, forecast_test, prefix="forecast"),
                }
            )
            predictions.append(
                pd.DataFrame(
                    {
                        "valid_time_utc": outer_test["valid_time_utc"],
                        "week_index": outer_test["week_index"],
                        "outer_fold": outer_fold.fold_index,
                        "actual_pv_power_w": y_test,
                        "oracle_actual_weather_prediction_w": oracle_actual_test,
                        "oracle_proxy_from_forecast_w": proxy_test,
                        "baseline_forecast_prediction_w": baseline_test,
                        "forecast_prediction_w": forecast_test,
                    }
                )
            )

        oof_predictions = pd.concat(predictions, ignore_index=True).sort_values(
            "valid_time_utc"
        ).reset_index(drop=True)
        metrics_frame = pd.DataFrame(fold_metrics).sort_values("outer_fold").reset_index(drop=True)
        metric_columns = [
            column
            for column in metrics_frame
            if column.endswith("_mae_w") or column.endswith("_rmse_w")
        ]
        average_fold_metrics = {
            column: float(metrics_frame[column].mean()) for column in metric_columns
        }
        actual = oof_predictions["actual_pv_power_w"].to_numpy(dtype=float)
        pooled_oof_metrics = {
            **_metrics(
                actual,
                oof_predictions["oracle_actual_weather_prediction_w"].to_numpy(dtype=float),
                prefix="oracle",
            ),
            **_metrics(
                actual,
                oof_predictions["baseline_forecast_prediction_w"].to_numpy(dtype=float),
                prefix="baseline",
            ),
            **_metrics(
                actual,
                oof_predictions["forecast_prediction_w"].to_numpy(dtype=float),
                prefix="forecast",
            ),
        }
        return PVExperimentResult(
            oof_predictions=oof_predictions,
            fold_metrics=metrics_frame,
            average_fold_metrics=average_fold_metrics,
            pooled_oof_metrics=pooled_oof_metrics,
        )

    def _inner_oof_oracle_proxy(self, outer_train: pd.DataFrame, outer_fold: int) -> np.ndarray:
        splitter = SeasonalWeekKFold(
            self.inner_splits,
            random_state=self.random_state + 10_000 + outer_fold,
        )
        proxy = np.full(len(outer_train), np.nan, dtype=float)
        for inner_fold in splitter.split_with_metadata(outer_train):
            oracle = self.oracle_factory(
                self.random_state + 20_000 + outer_fold * 100 + inner_fold.fold_index
            )
            inner_train = outer_train.iloc[inner_fold.train_indices]
            inner_test = outer_train.iloc[inner_fold.test_indices]
            oracle.fit(_oracle_features(inner_train, weather_source="actual"), inner_train[PV_TARGET])
            proxy[inner_fold.test_indices] = _nonnegative(
                oracle.predict(_oracle_features(inner_test, weather_source="forecast"))
            )
        if np.isnan(proxy).any():
            raise RuntimeError("Inner cross-fitting did not create every Oracle proxy value")
        return proxy


def _oracle_features(frame: pd.DataFrame, *, weather_source: str) -> pd.DataFrame:
    if weather_source not in {"actual", "forecast"}:
        raise ValueError("weather_source must be 'actual' or 'forecast'")
    prefix = f"weather_{weather_source}_"
    weather_columns = [f"{prefix}{variable}" for variable in WEATHER_VARIABLES]
    features = frame[weather_columns].reset_index(drop=True).copy()
    features.columns = list(WEATHER_VARIABLES)
    return pd.concat([features, frame[list(CONTEXT_FEATURES)].reset_index(drop=True)], axis=1)


def _forecast_features(
    frame: pd.DataFrame,
    oracle_proxy: np.ndarray | None = None,
) -> pd.DataFrame:
    features = _oracle_features(frame, weather_source="forecast")
    if oracle_proxy is not None:
        if len(features) != len(oracle_proxy):
            raise ValueError("Oracle proxy length does not match the forecasting frame")
        features["oracle_proxy_pv_w"] = oracle_proxy
    return features


def _validate_model_frame(frame: pd.DataFrame) -> None:
    required = {
        PV_TARGET,
        "week_index",
        "valid_time_utc",
        *CONTEXT_FEATURES,
        *[f"weather_actual_{variable}" for variable in WEATHER_VARIABLES],
        *[f"weather_forecast_{variable}" for variable in WEATHER_VARIABLES],
    }
    missing = sorted(required.difference(frame.columns))
    if missing:
        raise KeyError(f"PV modelling frame is missing columns: {', '.join(missing)}")
    if frame[list(required)].isna().any().any():
        raise ValueError("PV modelling frame contains missing values in required columns")


def _default_model_factory(random_state: int) -> RegressorMixin:
    return HistGradientBoostingRegressor(
        learning_rate=0.05,
        max_iter=100,
        max_leaf_nodes=31,
        l2_regularization=1.0,
        random_state=random_state,
    )


def _metrics(y_true: np.ndarray, y_pred: np.ndarray, *, prefix: str) -> dict[str, float]:
    error = y_true - y_pred
    return {
        f"{prefix}_mae_w": float(np.mean(np.abs(error))),
        f"{prefix}_rmse_w": float(np.sqrt(np.mean(np.square(error)))),
    }


def _nonnegative(prediction: np.ndarray) -> np.ndarray:
    """Apply the physical lower bound for PV power forecasts."""

    return np.maximum(np.asarray(prediction, dtype=float), 0.0)
